import type { RPDTemplate } from './types.js';

export const RPD_TEMPLATES: RPDTemplate[] = [
  {
    id: 'rpd-pink-deal',
    name: 'Pink Deal',
    layout: 'hero-deal',
    description: 'High-impact deal-first fashion composition.',
    supportedAngles: ['price', 'value'],
    supportedObjectives: ['conversion'],
    minImages: 1,
    supportsModel: true,
    supportsPrice: true,
    priority: 10,
  },
  {
    id: 'rpd-editorial',
    name: 'Editorial Style',
    layout: 'editorial',
    description: 'Fashion-editorial composition focused on styling.',
    supportedAngles: ['style', 'trend'],
    supportedObjectives: ['discovery', 'engagement'],
    minImages: 1,
    supportsModel: true,
    supportsPrice: false,
    priority: 8,
  },
  {
    id: 'rpd-colour-grid',
    name: 'Split Fashion',
    layout: 'split-product',
    description: 'Balanced product and information composition.',
    supportedAngles: ['style', 'occasion', 'value'],
    supportedObjectives: ['discovery', 'conversion'],
    minImages: 2,
    supportsModel: true,
    supportsPrice: true,
    priority: 7,
  },
  {
    id: 'rpd-lookbook',
    name: 'Model Focus',
    layout: 'model-first',
    description: 'Model-led fashion presentation.',
    supportedAngles: ['style', 'trend', 'occasion'],
    supportedObjectives: ['discovery', 'engagement'],
    minImages: 1,
    supportsModel: true,
    supportsPrice: false,
    priority: 9,
  },
  {
    id: 'rpd-minimal',
    name: 'Minimal Deal',
    layout: 'minimal-price',
    description: 'Clean product-first price composition.',
    supportedAngles: ['price', 'value'],
    supportedObjectives: ['conversion'],
    minImages: 1,
    supportsModel: false,
    supportsPrice: true,
    priority: 6,
  },
];
