-- RPD Money Engine production schema (Supabase/Postgres)
create table if not exists products (
  id text primary key,
  source_url text not null unique,
  title text,
  platform text,
  price numeric,
  mrp numeric,
  discount_percent numeric,
  images jsonb not null default '[]'::jsonb,
  raw_product jsonb,
  qualification jsonb,
  published boolean not null default false,
  affiliate_link_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists affiliate_links (
  id text primary key,
  product_id text not null,
  network text not null,
  destination_url text not null,
  label text,
  clicks bigint not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists affiliate_links_product_idx on affiliate_links(product_id);
create index if not exists affiliate_links_network_idx on affiliate_links(network);
create index if not exists products_published_idx on products(published);
create index if not exists products_affiliate_idx on products(affiliate_link_id);

create table if not exists affiliate_events (
  id bigint generated by default as identity primary key,
  link_id text references affiliate_links(id) on delete cascade,
  event_type text not null check (event_type in ('click','conversion')),
  content_id text,
  platform text,
  value numeric,
  commission numeric,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists affiliate_events_link_idx on affiliate_events(link_id);
create index if not exists affiliate_events_created_idx on affiliate_events(created_at desc);

alter table products enable row level security;
alter table affiliate_links enable row level security;
alter table affiliate_events enable row level security;
