import { randomBytes } from 'node:crypto';
import { dbSelect, dbUpsert, dbUpdate, localRead, localWrite, requireProductionStorage, useSupabase } from './storage.js';

export type StoredProduct={id:string;sourceUrl:string;title:string;platform:string;price:number|null;mrp:number|null;discountPercent:number|null;images:string[];product:any;qualification:any;published:boolean;affiliateLinkId?:string;createdAt:string;updatedAt:string};
const file='products.json';
const idFor=(url:string)=>'prod_'+randomBytes(9).toString('base64url');
const fromDb=(r:any):StoredProduct=>({id:r.id,sourceUrl:r.source_url,title:r.title||'',platform:r.platform||'',price:r.price??null,mrp:r.mrp??null,discountPercent:r.discount_percent??null,images:r.images||[],product:r.raw_product??null,qualification:r.qualification??null,published:Boolean(r.published),affiliateLinkId:r.affiliate_link_id||undefined,createdAt:r.created_at,updatedAt:r.updated_at});
const toDb=(p:StoredProduct)=>({id:p.id,source_url:p.sourceUrl,title:p.title,platform:p.platform,price:p.price,mrp:p.mrp,discount_percent:p.discountPercent,images:p.images,raw_product:p.product,qualification:p.qualification,published:p.published,affiliate_link_id:p.affiliateLinkId||null,created_at:p.createdAt,updated_at:p.updatedAt});
export async function upsertProduct(product:any,qualification:any):Promise<StoredProduct>{
 requireProductionStorage(); const now=new Date().toISOString();
 if(useSupabase()){const existing=await dbSelect<any>('products','?source_url=eq.'+encodeURIComponent(product.sourceUrl)+'&limit=1');const p:StoredProduct={id:existing[0]?.id||idFor(product.sourceUrl),sourceUrl:product.sourceUrl,title:product.title?.value||'',platform:new URL(product.sourceUrl).hostname,price:product.price?.value??null,mrp:product.mrp?.value??null,discountPercent:product.discountPercent?.value??null,images:Array.isArray(product.images)?product.images:[],product,qualification,published:existing[0]?Boolean(existing[0].published):false,affiliateLinkId:existing[0]?.affiliate_link_id||undefined,createdAt:existing[0]?.created_at||now,updatedAt:now};return fromDb(await dbUpsert<any>('products',toDb(p),'source_url'))}
 const all=await localRead<StoredProduct[]>(file,[]),existing=all.find(p=>p.sourceUrl===product.sourceUrl);const p:StoredProduct={id:existing?.id||idFor(product.sourceUrl),sourceUrl:product.sourceUrl,title:product.title?.value||'',platform:new URL(product.sourceUrl).hostname,price:product.price?.value??null,mrp:product.mrp?.value??null,discountPercent:product.discountPercent?.value??null,images:Array.isArray(product.images)?product.images:[],product,qualification,published:existing?.published??false,affiliateLinkId:existing?.affiliateLinkId,createdAt:existing?.createdAt||now,updatedAt:now};const i=all.findIndex(x=>x.id===p.id);if(i>=0)all[i]=p;else all.push(p);await localWrite(file,all);return p;
}
export async function listProducts(publishedOnly=false):Promise<StoredProduct[]>{requireProductionStorage();if(useSupabase()){const q=publishedOnly?'?published=eq.true&affiliate_link_id=not.is.null&order=updated_at.desc':'?order=updated_at.desc';return (await dbSelect<any>('products',q)).map(fromDb)}const all=await localRead<StoredProduct[]>(file,[]);return publishedOnly?all.filter(p=>p.published&&p.affiliateLinkId):all}
export async function getProduct(id:string):Promise<StoredProduct|null>{requireProductionStorage();if(useSupabase()){const r=await dbSelect<any>('products','?id=eq.'+encodeURIComponent(id)+'&limit=1');return r[0]?fromDb(r[0]):null}return (await localRead<StoredProduct[]>(file,[])).find(p=>p.id===id)||null}
export async function publishProduct(id:string,published:boolean,affiliateLinkId?:string):Promise<StoredProduct|null>{requireProductionStorage();if(useSupabase()){const patch:any={published,updated_at:new Date().toISOString()};if(affiliateLinkId!==undefined)patch.affiliate_link_id=affiliateLinkId;const r=await dbUpdate<any>('products',patch,'id=eq.'+encodeURIComponent(id));return r?fromDb(r):null}const all=await localRead<StoredProduct[]>(file,[]),p=all.find(x=>x.id===id);if(!p)return null;p.published=published;if(affiliateLinkId!==undefined)p.affiliateLinkId=affiliateLinkId;p.updatedAt=new Date().toISOString();await localWrite(file,all);return p}
